if strings command not found

diff --git a/build/sealion_classic_build/configure b/build/sealion_classic_build/configure
--- a/build/sealion_classic_build/configure
+++ b/build/sealion_classic_build/configure
@@ -27,11 +27,16 @@ if [ $KERNEL_VERSION -le 2 ] ; then
 fi
 
 # check for glibc version (min 2.4)
-LIBCPATH="`find /lib* | grep libc.so.6 | head -1`"
+LIBCPATH="`find /lib*/ | grep libc.so.6 | head -1`"
 if [ -z "$LIBCPATH" ]; then
     echo "Error: GLIBC_2.4 not found. Exiting"
     exit 1
 else
+    STRINGS="`which strings`"
+    if [ -z "$STRINGS" ]; then
+        echo "Error: strings command not available. Please install binutils package."
+        exit 1  
+    fi
     LIBC24="`strings $LIBCPATH | grep 'GLIBC_2.4'`"
     if [ -z "$LIBC24" ]; then
         echo "Error: SeaLion agent requires GLIBC_2.4 or above. Exiting"
@@ -53,7 +58,7 @@ fi
 
 # check if curl command is installed for registration and upgrade
 if [ "`which curl`" == "" ]; then
-    echo "Curl command not found. Please install curl..."
+    echo "Curl command not found. Please install curl."
     exit 1
 fi
 
