added try catch to check for spawn failure, installer changes for openSuse

diff --git a/build/sealion_classic_build/configure b/build/sealion_classic_build/configure
--- a/build/sealion_classic_build/configure
+++ b/build/sealion_classic_build/configure
@@ -1,16 +1,42 @@
 #!/bin/bash
 PLATFORM=`uname -m`
 BINARY_PLATFORM="x86_64"
-USAGE="Usage: ./configure \n\t-o <Organisation Token> \n\t[-H <Hostname>] \n\t[-c <category name>] \n\t [-h for help]"
+USAGE="Usage: ./configure \n\t-o <Organisation Token> \n\t[-H <Hostname>] \n\t[-c <Category name>] \n\t[-x <Proxy address>] \n\t[-h for help]"
 
+# check platform compatibility
+# check if linux
 if [ "`uname -s`" != "Linux" ]; then
-    echo "SeaLion agent works on Linux only" >&2
+    echo "Error: SeaLion agent works on Linux only" >&2
     exit 1
 fi
 
+PLATFORM=`uname -m`
+# check for platform architecture
 if [[ "$PLATFORM" != "x86_64" && "$PLATFORM" != "i686" ]]; then
-    echo "Platform not supported" >&2
+    echo "Error: Platform not supported" >&2
     exit 1
+fi
+
+# check for kernel version (min 2.6)
+eval $(uname -r | awk -F'.' '{printf("KERNEL_VERSION=%s KERNEL_MAJOR=%s\n", $1, $2)}')
+if [ $KERNEL_VERSION -le 2 ] ; then
+    if [[ $KERNEL_VERSION -eq 1 || $KERNEL_MAJOR -lt 6 ]]; then
+        echo "Error: SeaLion agent requires kernel 2.6 or above. Exiting" >&2
+        exit 1
+    fi
+fi
+
+# check for glibc version (min 2.4)
+LIBCPATH="`find /lib* | grep libc.so.6 | head -1`"
+if [ -z "$LIBCPATH" ]; then
+    echo "Error: GLIBC_2.4 not found. Exiting"
+    exit 1
+else
+    LIBC24="`strings $LIBCPATH | grep 'GLIBC_2.4'`"
+    if [ -z "$LIBC24" ]; then
+        echo "Error: SeaLion agent requires GLIBC_2.4 or above. Exiting"
+        exit 1
+    fi
 fi
 
 if [[ "$PLATFORM" != "$BINARY_PLATFORM" ]]; then
@@ -25,7 +51,9 @@ if [[ "$PLATFORM" != "$BINARY_PLATFORM" ]]; then
     exit 1
 fi
 
-while getopts a:o:c:v:hH: OPT ; do
+HTTPPROXY=
+
+while getopts a:o:x:c:v:hH: OPT ; do
     case "$OPT" in
         v)
             version=$OPTARG
@@ -39,6 +67,9 @@ while getopts a:o:c:v:hH: OPT ; do
         h)
             printf "$USAGE \n" >&1
             exit 0
+        ;;
+        x)
+            HTTPPROXY=$OPTARG
         ;;
         o)
         if [ -z $org_token ] ; then
@@ -69,7 +100,11 @@ fi
 
 echo "Generating installer script..."
 
-sed '0,/version=/{s/version=/version=\"'"$version"'\"/}; 0,/agent_id=/{s/agent_id=/agent_id=\"'"$agent_id"'\"/}; 0,/host=/{s/host=/host=\"'"$host"'\"/}; 0,/org_token=/{s/org_token=/org_token=\"'"$org_token"'\"/}; 0,/category=/{s/category=/category=\"'"$category"'\"/};' installer.in > installer.out
+sed '0,/version=/{s/version=/version=\"'"$version"'\"/}; 0,/agent_id=/{s/agent_id=/agent_id=\"'"$agent_id"'\"/}; 0,/host=/{s/host=/host=\"'"$host"'\"/}; 0,/org_token=/{s/org_token=/org_token=\"'"$org_token"'\"/}; 0,/category=/{s/category=/category=\"'"$category"'\"/}; 0,/HTTPPROXY=/{s$HTTPPROXY=$HTTPPROXY=\"'"$HTTPPROXY"'\"$};' installer.in > installer.out
+if [ $? -ne 0 ] ; then
+    echo "Error: Failed to generate installer.out. Aborting"
+    exit 1
+fi
 
 chmod +x installer.out
 
diff --git a/build/sealion_classic_build/installer.in b/build/sealion_classic_build/installer.in
--- a/build/sealion_classic_build/installer.in
+++ b/build/sealion_classic_build/installer.in
@@ -5,7 +5,14 @@ agent_id=
 host=
 org_token=
 category=
+HTTPPROXY=
+CURL_COMMAND_PROXY=
+if [[ ! -z $HTTPPROXY ]] ; then
+    CURL_COMMAND_PROXY="-x $HTTPPROXY"
+fi
+
 REGISTRATION_URL="<registration-url>"
+PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
 
 TMP_FILE_PATH=`mktemp -d /tmp/sealion-agent.XXXX` || exit 1
 TMP_DATA_NAME=$TMP_FILE_PATH"/sealion-data.tmp"
@@ -27,12 +34,14 @@ fi
 
 clean_up()
 {
-
     echo "Removing files generated for installation..."
         for (( i = 1 ; i < $1 ; i++ )) 
         do
-            rm -f /etc/rc$i.d/${SYMLINK_PATHS[$i]}20sealion
+            VAR_NAME="RC"$i"_PATH"/${SYMLINK_PATHS[$i]}99sealion
+            rm -f $VAR_NAME
         done
+        
+        rm -f $INIT_D_PATH/sealion
         rm -rf $TMP_FILE_PATH
         rm -rf $INSTALLATION_DIRECTORY
     echo "Successfully removed files"
@@ -52,6 +61,12 @@ get_JSON_value()
     
     return 0
 }
+
+if [[ $EUID != 0 && -z $agent_id ]] ; then
+    echo "SeaLion agent installation requires super privilege" >&2
+    echo -e "Usage:\n sudo make install"
+    exit 116
+fi
 
 running=`pgrep sealion-node | wc -w`
 if [ $running -gt 0 ] ; then
@@ -74,7 +89,18 @@ if [ -z $agent_id ] ; then
         exit 118
     fi
 
-    useradd -r -d $INSTALLATION_DIRECTORY $USERNAME 2> /dev/null
+    groupadd -r $USERNAME 2> /dev/null
+    tempVar=$?
+    if [ $tempVar -ne 0 ] ; then
+        if [ $tempVar -ne 9 ] ; then
+            echo "Error: Group 'sealion' creation failed!" >&2
+            rm -r $INSTALLATION_DIRECTORY
+            exit 1
+        fi
+    fi
+    echo "Created 'sealion' group successfully" >&1
+    
+    useradd -r -d $INSTALLATION_DIRECTORY -g $USERNAME $USERNAME 2> /dev/null
     tempVar=$?
     if [ $tempVar -ne 0 ] ; then
         if [ $tempVar -ne 9 ] ; then
@@ -97,6 +123,7 @@ echo "Copying files to /usr/local/sealion-agent..." >&1
         echo "Error: Installation failed" >&2
         if [ $is_root -eq 1 ] ; then
             userdel sealion
+            groupdel sealion
             rm -rf $INSTALLATION_DIRECTORY
             rm -rf $TMP_FILE_PATH
             if [ $? -ne 0 ] ; then
@@ -110,36 +137,58 @@ echo "Files copied successfully" >&1
 cd $INSTALLATION_DIRECTORY
 
 if [ $is_root -eq 1 ] ; then
+
+    RC1_PATH=`find /etc/ -type d -name rc1.d`
+    RC2_PATH=`find /etc/ -type d -name rc2.d`
+    RC3_PATH=`find /etc/ -type d -name rc3.d`
+    RC4_PATH=`find /etc/ -type d -name rc4.d`
+    RC5_PATH=`find /etc/ -type d -name rc5.d`
+    RC6_PATH=`find /etc/ -type d -name rc6.d`
+    INIT_D_PATH=`find /etc/ -type d -name init.d`
+
+    if [[ -z $RC1_PATH || -z $RC2_PATH || -z $RC3_PATH || -z $RC4_PATH || -z $RC5_PATH || -z $RC6_PATH || -z $INIT_D_PATH ]] ; then
+        echo "Error: Could not locate init.d/rc folders" >&2
+        userdel sealion
+        groupdel sealion
+        rm -rf $INSTALLATION_DIRECTORY
+        rm -rf $TMP_FILE_PATH
+        if [ $? -ne 0 ] ; then
+            echo "Error: Failed to delete temporary files" >&2
+        fi
+        exit 115
+    fi
+
     chown -R $USERNAME:$USERNAME $INSTALLATION_DIRECTORY
 
-    ln -sf $INIT_FILE /etc/init.d/sealion
+    ln -sf $INIT_FILE $INIT_D_PATH/sealion
     chmod +x $INIT_FILE
-    chown -h $USERNAME:$USERNAME /etc/init.d/sealion
-
+    
     for (( i = 1 ; i < 7 ; i++ )) 
     do
-        ln -sf $INIT_FILE /etc/rc$i.d/${SYMLINK_PATHS[$i]}20sealion
+        VAR_NAME="RC"$i"_PATH"
+        ln -sf $INIT_FILE ${!VAR_NAME}/${SYMLINK_PATHS[$i]}99sealion
         if [ $? -ne 0 ] ; then
             echo "Error: Unable to update init.d files. Aborting" >&2
             clean_up $i
             exit 1
         fi
-        chown -h $USERNAME:$USERNAME /etc/rc$i.d/${SYMLINK_PATHS[$i]}20sealion
     done
     
     echo "Installed SeaLion as a service" >&1
 fi
 
 if [ -z $agent_id ] ; then
+
+
     if [ -z "$category" ] ; then
-        return_code=`curl -s -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "{\"orgToken\":\"$org_token\", \"name\":\"$host\", \"ref\":\"tarball\"}"  $REGISTRATION_URL -o $TMP_DATA_NAME`
+        return_code=`curl -s $CURL_COMMAND_PROXY -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "{\"orgToken\":\"$org_token\", \"name\":\"$host\", \"ref\":\"curl\"}"  $REGISTRATION_URL -o $TMP_DATA_NAME`
         if [[ $? -ne 0 || $return_code -ne 201 ]] ; then
             clean_up 6
             echo "Error: Registration failed. Aborting" >&2
             exit 123
         fi
     else
-        return_code=`curl -s -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "{\"orgToken\":\"$org_token\", \"name\":\"$host\", \"category\":\"$category\", \"ref\":\"tarball\"}"  $REGISTRATION_URL -o $TMP_DATA_NAME`
+        return_code=`curl -s $CURL_COMMAND_PROXY -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "{\"orgToken\":\"$org_token\", \"name\":\"$host\", \"category\":\"$category\", \"ref\":\"curl\"}"  $REGISTRATION_URL -o $TMP_DATA_NAME`
         if [[ $? -ne 0 || $return_code -ne 201 ]] ; then
             clean_up 6
             echo "Error: Registration failed. Aborting" >&2
@@ -176,12 +225,16 @@ if [ $? -ne 0 ] ; then
     echo "Error: Failed to delete temporary files" >&2
 fi
 
-if [ -n $http_proxy ] ; then
-    HTTPPROXY=$http_proxy
-else
-    if [ -n $HTTP_PROXY ] ;then
-        HTTPPROXY=$HTTP_PROXY                
+if [ -z $HTTPPROXY ] ; then
+
+    if [ -n $http_proxy ] ; then
+        HTTPPROXY=$http_proxy
+    else
+        if [ -n $HTTP_PROXY ] ;then
+            HTTPPROXY=$HTTP_PROXY                
+        fi
     fi
+    
 fi
 
 if [[ -n $HTTPPROXY && ! -f $PROXY_FILE_PATH ]] ; then
@@ -191,7 +244,6 @@ fi
 if [ $is_root -eq 1 ] ; then
     chown -R $USERNAME:$USERNAME etc/config
 fi 
-
     
 echo "Starting agent..." >&1
 $INIT_FILE start
diff --git a/sealion-agent/etc/sealion b/sealion-agent/etc/sealion
--- a/sealion-agent/etc/sealion
+++ b/sealion-agent/etc/sealion
@@ -2,131 +2,156 @@
 
 ### BEGIN INIT INFO
 # Provides:          sealion
-# Required-Start:    
+# Required-Start:       
 # Required-Stop:     
 # Should-Start:      
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Sealion agent for 
-# Description:       Sealion is cloud based server debugging tool.
-#                    This is Sealion's Agent to send monitoring data to Sealion server
+# Short-Description: SeaLion agent
+# Description:       SeaLion is cloud based server debugging tool.
+#                    This is SeaLion's Agent to send monitoring data to SeaLion server
 # 
 ### END INIT INFO
 
+
+SUSE=0
 LOCK_FILE=/usr/local/sealion-agent/var/sealion/sealion.pid
 
 cd /usr/local/sealion-agent/
-if [ $? -ne 0 ] ; then
-    exit 1
-fi
+if [ $? -ne 0 ] ; then      
+    exit 1                  
+fi                          
+
+if [ $((`grep SUSE /etc/issue -c`)) -gt 0 ]; then
+        SUSE=1;                                  
+fi                                               
+
+if [ $SUSE -eq 1 ]; then
+        . /lib/lsb/init-functions   
+        . /etc/rc.status            
+        rc_reset                    
+fi                                  
+
+#
+# Function that starts the SeaLion agent's service
+#                                                 
+do_start()                                        
+{                                                 
+    if [ ! -s $LOCK_FILE ]                        
+        then                                      
+                ./bin/sealion-node index.js start 
+                RETURN_VALUE=$?                   
+                if [ $SUSE -eq 1  ] ; then        
+                        rc_status             
+                        sleep 1                   
+                fi                                
+                return $RETURN_VALUE              
+        else                                      
+            running=`pgrep sealion-node | wc -w`  
+            if [ $running -eq 0 ] ; then          
+                rm -f $LOCK_FILE                  
+                if [ $? -eq 0 ] ; then            
+                    ./bin/sealion-node index.js start
+                    RETURN_VALUE=$?                  
+                    if [ $SUSE -eq 1 ] ; then        
+                        rc_status                
+                        sleep 1                      
+                    fi                               
+                    return $RETURN_VALUE             
+                fi                                   
+            fi                                       
+            return 1                                 
+        fi                                           
+}                                                    
 
 
 #
-# Function that starts the sealion agent's service
-#
-do_start()
-{
-    if [ ! -s $LOCK_FILE ] 
-	then
-        ./bin/sealion-node index.js start
-        RETURN_VALUE=$?
-        return $RETURN_VALUE
-	else
-	    running=`pgrep sealion-node | wc -w`
-	    if [ $running -eq 0 ] ; then
-	        rm -f $LOCK_FILE
-	        if [ $? -eq 0 ] ; then
-	            ./bin/sealion-node index.js start
-	            RETURN_VALUE=$?
-                return $RETURN_VALUE
-	        fi
-	    fi
-	    return 1
-	fi
-}
-
-
-#
-# Function that returns Sealion agent's status
-#
-get_status()
-{
-    running=`pgrep sealion-node | wc -w`
-    if [ $running -gt 0 ] ; then
-        return 1
-    fi
+# Function that returns SeaLion agent's status
+#                                             
+get_status()                                  
+{                                             
+    running=`pgrep sealion-node | wc -w`      
+    if [ $running -gt 0 ] ; then              
+        return 1                              
+    fi                                        
 
     return 0
-}
+}           
 
 #
-# Function that stops the sealion agent's service
-#
-do_stop()
-{
+# Function that stops the SeaLion agent's service
+#                                                
+do_stop()                                        
+{                                                
 
     if [ -s $LOCK_FILE ]
-	then
-	    running=`pgrep sealion-node | wc -w`
+        then            
+            running=`pgrep sealion-node | wc -w`
 
-    	if [ $running -gt 0 ] ; then
-    	    ./bin/sealion-node index.js stop
-    	    RETURN_VALUE=$?
-    	    rm -f $LOCK_FILE
-	        return $RETURN_VALUE
-    	fi
-    	
-	    rm -f $LOCK_FILE
-	    return 0
-	else
-	    return 1
-	fi
-}
+        if [ $running -gt 0 ] ; then
+            ./bin/sealion-node index.js stop
+            RETURN_VALUE=$?                 
+            if [ $SUSE -eq 1 ] ; then       
+                rc_status
+            fi                              
+            rm -f $LOCK_FILE                
+            return $RETURN_VALUE            
+        fi                                  
+                                            
+            rm -f $LOCK_FILE                
+            return 0                        
+        else                                
+            return 1                        
+        fi                                  
+}                                           
 
 
 case "$1" in
-  start)
-	do_start
-	case "$?" in
-		0) 
-		    echo "Sealion service started successfully" 
-		;;
-		1) 
-		    echo "Sealion service already running" 
-		;;
-	esac
-	;;
-  stop)
-	do_stop
-	case "$?" in
-		0) 
-		    echo "Sealion service stopped successfully" 
-		;;
-		1) 
-		    echo "Sealion service not running" 
-		;;
-	esac
-	;;
+  start)    
+        do_start
+        case "$?" in
+                0)  
+                    echo "sealion service started successfully"
+                ;;                                              
+                1)                                              
+                    echo "sealion service already running"
+                ;;                                              
+        esac                                                    
+        ;;                                                      
+  stop)                                                         
+        do_stop                                                 
+        case "$?" in                                            
+                0)                                              
+                    echo "sealion service stopped successfully"
+                ;;                                              
+                1)
+                    echo "sealion service not running"
+                ;;
+        esac
+        ;;
   restart|force-reload)
-	do_stop
-	do_start
-	case "$?" in
-		0)
-		    echo "Sealion service restarted successfully"
-		;;
-		*)
-	      echo "Failed to restart Sealion Service"
-	    ;;
-	esac
+        do_stop
+        do_start
+        case "$?" in
+                0)
+                    echo "sealion service restarted successfully"
+                ;;
+                *)
+              echo "Failed to restart sealion Service"
+            ;;
+        esac
+        if [ $SUSE -eq 1 ] ; then
+                rc_status
+        fi
     ;;
   status)
     get_status
     case "$?" in
       0)
-        echo "Sealion service is not running"
+        echo "sealion service is not running"
       ;;
       1)
-        echo "Sealion service is running"
+        echo "sealion service is running"
       ;;
     esac
     ;;
