restarting agent on crash and other bug fixes

diff --git a/build/sealion_classic_build/configure b/build/sealion_classic_build/configure
--- a/build/sealion_classic_build/configure
+++ b/build/sealion_classic_build/configure
@@ -51,6 +51,12 @@ if [[ "$PLATFORM" != "$BINARY_PLATFORM" ]]; then
     exit 1
 fi
 
+# check if curl command is installed for registration and upgrade
+if [ "`which curl`" == "" ]; then
+    echo "Curl command not found. Please install curl..."
+    exit 1
+fi
+
 HTTPPROXY=
 
 while getopts a:o:x:c:v:hH: OPT ; do
diff --git a/sealion-agent/etc/sealion b/sealion-agent/etc/sealion
--- a/sealion-agent/etc/sealion
+++ b/sealion-agent/etc/sealion
@@ -16,6 +16,7 @@
 
 SUSE=0
 LOCK_FILE=/usr/local/sealion-agent/var/sealion/sealion.pid
+FUNCTION_RETURN_VALUE=0
 
 cd /usr/local/sealion-agent/
 if [ $? -ne 0 ] ; then      
@@ -36,32 +37,37 @@ fi
 # Function that starts the SeaLion agent's service
 #                                                 
 do_start()                                        
-{                                                 
+{
+    FUNCTION_RETURN_VALUE=0
     if [ ! -s $LOCK_FILE ]                        
-        then                                      
-                ./bin/sealion-node index.js start 
-                RETURN_VALUE=$?                   
-                if [ $SUSE -eq 1  ] ; then        
-                        rc_status             
-                        sleep 1                   
-                fi                                
-                return $RETURN_VALUE              
-        else                                      
-            running=`pgrep sealion-node | wc -w`  
-            if [ $running -eq 0 ] ; then          
-                rm -f $LOCK_FILE                  
-                if [ $? -eq 0 ] ; then            
-                    ./bin/sealion-node index.js start
-                    RETURN_VALUE=$?                  
-                    if [ $SUSE -eq 1 ] ; then        
-                        rc_status                
-                        sleep 1                      
-                    fi                               
-                    return $RETURN_VALUE             
-                fi                                   
-            fi                                       
-            return 1                                 
-        fi                                           
+    then
+        ./bin/sealion-node index.js start
+        RETURN_VALUE=$?
+        if [ $SUSE -eq 1  ] ; then
+                rc_status
+                sleep 1
+        fi
+        return $RETURN_VALUE
+    else
+        running=`pgrep sealion-node | wc -w`
+        if [ $running -eq 0 ] ; then
+            rm -f $LOCK_FILE
+            if [ $? -eq 0 ] ; then
+                ./bin/sealion-node index.js start
+                RETURN_VALUE=$?
+                if [ $SUSE -eq 1 ] ; then
+                    rc_status
+                    sleep 1
+                fi
+                return $RETURN_VALUE
+            else
+                echo "Failed to remove lock file to start service."
+                return 1
+            fi
+        fi
+        FUNCTION_RETURN_VALUE=-1
+        return 1
+    fi
 }                                                    
 
 
@@ -82,27 +88,29 @@ get_status()
 # Function that stops the SeaLion agent's service
 #                                                
 do_stop()                                        
-{                                                
+{
+    FUNCTION_RETURN_VALUE=0
+    running=`pgrep sealion-node | wc -w`
+    if [ $running -gt 0 ] ; then
+        ./bin/sealion-node index.js stop
+        RETURN_VALUE=$?
+        if [ $SUSE -eq 1 ] ; then
+            rc_status
+        fi
+
+        if [ -s $LOCK_FILE ]
+        then
+            rm -f $LOCK_FILE
+        fi
+        return $RETURN_VALUE
+    fi
 
     if [ -s $LOCK_FILE ]
-        then            
-            running=`pgrep sealion-node | wc -w`
-
-        if [ $running -gt 0 ] ; then
-            ./bin/sealion-node index.js stop
-            RETURN_VALUE=$?                 
-            if [ $SUSE -eq 1 ] ; then       
-                rc_status
-            fi                              
-            rm -f $LOCK_FILE                
-            return $RETURN_VALUE            
-        fi                                  
-                                            
-            rm -f $LOCK_FILE                
-            return 0                        
-        else                                
-            return 1                        
-        fi                                  
+    then
+        rm -f $LOCK_FILE
+    fi
+    FUNCTION_RETURN_VALUE=-1
+    return 1
 }                                           
 
 
@@ -110,22 +118,36 @@ case "$1" in
   start)    
         do_start
         case "$?" in
-                0)  
+                0)
                     echo "sealion service started successfully"
-                ;;                                              
-                1)                                              
-                    echo "sealion service already running"
+                ;;
+                1)
+                    if [ $FUNCTION_RETURN_VALUE -eq -1 ] ;then
+                        echo "sealion service already running"
+                    else
+                        echo "Failed to start sealion service"
+                    fi
+                ;;
+                *)
+                    echo "Failed to start sealion service"
                 ;;                                              
         esac                                                    
         ;;                                                      
   stop)                                                         
         do_stop                                                 
         case "$?" in                                            
-                0)                                              
+                1)
+                    if [ $FUNCTION_RETURN_VALUE -eq -1 ] ; then
+                        echo "sealion service not running"
+                    else
+                        echo "Failed to stop sealion service"
+                    fi
+                ;;
+                0)
                     echo "sealion service stopped successfully"
                 ;;                                              
-                1)
-                    echo "sealion service not running"
+                *)
+                    echo "Failed to stop sealion service"
                 ;;
         esac
         ;;
@@ -133,11 +155,18 @@ case "$1" in
         do_stop
         do_start
         case "$?" in
-                0)
-                    echo "sealion service restarted successfully"
-                ;;
-                *)
-              echo "Failed to restart sealion Service"
+            1)
+                if [ $FUNCTION_RETURN_VALUE -eq -1 ]; then
+                    echo "sealion service already running"
+                else
+                    echo "Failed to restart sealion service"
+                fi
+            ;;
+            0)
+                echo "sealion service restarted successfully"
+            ;;
+            *)
+                echo "Failed to restart sealion Service"
             ;;
         esac
         if [ $SUSE -eq 1 ] ; then
