merged to master

diff --git a/build/sealion.sh.in b/build/sealion.sh.in
--- a/build/sealion.sh.in
+++ b/build/sealion.sh.in
@@ -1,8 +1,6 @@
 #! /bin/bash
 
-USAGE="Usage: curl -k https://agent.sealion.com | bash /dev/stdin \n\t-o <Organisation Token> \n\t[-H <Hostname>] \n\t[-c <comma seperated list of tags without spaces>] \n\t [-h for help]"
 OPTERR=0
-LOCK_FILE=/usr/local/sealion-agent/var/sealion/sealion.pid
 INIT_FILE=/etc/init.d/sealion
 TMP_FILE_PATH=/tmp/sealion-agent
 
@@ -18,9 +16,10 @@ clean_up()
 {
     for (( i = 0 ; i < $1 ; i++ )) 
     do
-        sudo rm -f /etc/rc$i.d/${SYMLINK_PATHS[$i]}20sealion
+        rm -f /etc/rc$i.d/${SYMLINK_PATHS[$i]}20sealion
     done
-    sudo rm -rf $TEMP_PATH        
+    rm -rf $TMP_FILE_PATH
+    rm -rf $INSTALLATION_DIRECTORY
 }
 
 
@@ -30,62 +29,51 @@ get_JSON_value()
         return 1
     fi 
     
-    JSON="'$@'"
+    JSON=$@
     
-    version=`python -c "import json;obj=json.loads($JSON);print obj[\"agentVersion\"]"` 
-    agent_token=`python -c "import json;obj=json.loads($JSON);print obj[\"agentToken\"]"`
-    already_registered=`python -c "import json;obj=json.loads($JSON);print obj[\"alreadyRegistered\"]"`
+    version=`echo $JSON | sed 's/.*"agentVersion"\s*:\s*\([0-9\.]*\)[,}].*/\1/'` 
+    agent_id=`echo $JSON | sed 's/.*"_id"\s*:\s*"\([0-9a-z]*\)"[,}].*/\1/'`
+    already_registered=`echo $JSON | sed 's/.*"alreadyRegistered"\s*:\s*\(0\|1\)[,}].*/\1/'`
+    
     return 0
 }
 
-running=`pgrep sealion-node | wc -w`
-if [ $running -gt 0 ] ; then
-    echo "SeaLion-Agent: Sealion service already running. Stopping the service"
-    $INIT_FILE stop
-fi
 
-while getopts a:o:c:v:hH: OPT ; do
+
+
+while getopts a:o:c:v:H: OPT ; do
     case "$OPT" in
         v)
             version=$OPTARG
         ;;
         a)
-            agent_token=$OPTARG
+            agent_id=$OPTARG
         ;;
         H)
             host=$OPTARG
         ;;
-        h)
-            printf "$USAGE \n" >&1
-            exit 0
-        ;;
         o)
         if [ -z $org_token ] ; then
             org_token=$OPTARG
-        else
-            echo "SeaLion-Agent Error: Organization token option is repeated. Quiting" >&2
-            exit 127
         fi
         ;;
         c)
             tags=$OPTARG
         ;;
-        \?)
-            echo "SeaLion-Agent Error: Invalid argument -$OPTARG" >&2
-            printf "$USAGE \n" >&2
-            exit 126
-        ;;
-        :)
-            echo "SeaLion-Agent Error: Option -$OPTARG requires an argument." >&2
-            exit 125
-        ;;
     esac
 done
 
-if [ -z $agent_token ] ; then
+running=`pgrep sealion-node | wc -w`
+if [ $running -gt 0 ] ; then
+    echo "Trying to stop SeaLion service"
+    $INIT_FILE stop
+    sleep 2
+fi
+
+if [ -z $agent_id ] ; then
 
     if [ -z $org_token ] ; then
-        echo "SeaLion-Agent Error: No Organization token is supplied. Quiting" >&2
+        echo "Error: No organization token found. Aborting" >&2
         exit 124
     fi
 
@@ -95,84 +83,39 @@ if [ -z $agent_token ] ; then
 
     mkdir -p $TMP_FILE_PATH
     if [ $? -ne 0 ] ; then
-        echo "SeaLion-Agent Error: Can't create temporary directory" >&2
+        echo "Error: Temporary directory creation failed. Aborting" >&2
         exit 1
     fi
-    
-    if [ -z $tags ] ; then
-        return_code=`curl -s -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "{\"orgToken\":\"$org_token\", \"name\":\"$host\"}" https://api.sealion.com/agents -o $TMP_DATA_NAME`
-        if [ $? -ne 0 -o $return_code -ne 200 ] ; then
-            echo "SeaLion-Agent Error: Download/Installation failed" >&2
-            exit 123
-        fi     
-    else
-        tags=\"$tags\"
-        tags=${tags//,/\",\"}
-        return_code=`curl -s -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "{\"orgToken\":\"$org_token\", \"name\":\"$host\", \"category\":[$tags]}" https://api.sealion.com/agents -o $TMP_DATA_NAME`
-        if [ $? -ne 0 -o $return_code -ne 200 ] ; then
-            echo "SeaLion-Agent Error: Download/Installation failed"
-            exit 123
-        fi
-    fi
-    
-    dataJSON=`cat $TMP_DATA_NAME`
-    
-    
-    get_JSON_value $dataJSON
-    if [ $? -ne 0 ] ; then
-        echo "SeaLion-Agent Error: Response parse error"    
-        exit 121
-    fi
-    
-    if [ -z $version ] ; then
-        echo "SeaLion-Agent Error: 'agent-version' not present in response. Please report the issue"
-        exit 119
-    fi    
-    
-    if [ -z $agent_token ] ; then
-        echo "SeaLion-Agent Error: 'agent-token' not present in response. Please report the issue"
-        exit 120
-    fi
-    
-    if [ -z $already_registered ] ; then
-        echo "SeaLion-Agent Error: 'already-registered' not present in response. Please report the issue"
-    else
-        if [ $already_registered -eq 1 ]; then
-            echo "SeaLion-Agent Warning: Agent may be already registered" >&1
-        fi
-    fi
-    
+
     is_root=1    
         
     mkdir -p $INSTALLATION_DIRECTORY
     if [ $? -ne 0 ] ; then
-        echo "SeaLion-Agent Error: Can't create directory!!!" >&2
+        echo "Error: Directory creation failed!!!" >&2
+        exit 118
     fi
 
-    echo "SeaLion-Agent: Creating SeaLion Agent's User..." >&1
     useradd -r -d $INSTALLATION_DIRECTORY $USERNAME 2> /dev/null
     tempVar=$?
     if [ $tempVar -ne 0 ] ; then
-        if [ $tempVar -eq 9 ] ; then
-            echo "SeaLion-Agent Warning: Username 'sealion' already exists, using same user" >&1
-        else
-            echo "SeaLion-Agent Error: Can't create user!!!" >&2
+        if [ $tempVar -ne 9 ] ; then
+            echo "Error: User 'sealion' creation failed!" >&2
             rm -r $INSTALLATION_DIRECTORY
             exit 1
         fi
     fi
-    echo "SeaLion-Agent: SeaLion Agent's User creation successful" >&1
+    echo "Created 'sealion' user successfully" >&1
 
 else
 
     if [ -z $version ] ; then 
-        echo "SeaLion-Agent Error: Agent-version not found"
+        echo "Error: Agent-version not found"
         exit 121
     fi
-
+    
 fi    
 
-echo "SeaLion-Agent: Extracting Files..." >&1
+echo "Extracting files to /usr/local/sealion-agent..." >&1
     
     MATCH=$( grep --text --line-number '^SEALION_TARFILE:$' $0 | cut -d ':' -f 1 )
     TAR_FILE_START=$(( MATCH + 1 ))
@@ -180,65 +123,113 @@ echo "SeaLion-Agent: Extracting Files..." >&1
     tail -n +$TAR_FILE_START $0 | tar -xzf - -C $INSTALLATION_DIRECTORY --overwrite
     
     if [ $? -ne 0 ] ; then
-        echo "SeaLion-Agent Error: Installation failed" >&2
+        echo "Error: Installation failed" >&2
         if [ $is_root -eq 1 ] ; then
             userdel sealion
             rm -rf $INSTALLATION_DIRECTORY
             rm -rf $TMP_FILE_PATH
             if [ $? -ne 0 ] ; then
-                echo "SeaLion-Agent Error: Error in deleting temporary files" >&2
+                echo "Error: Failed to delete temporary files" >&2
             fi
         fi
         exit 1
     fi
 
-echo "SeaLion-Agent: Files Extracted Successfully" >&1
+echo "Files extracted successfully" >&1
 
 cd $INSTALLATION_DIRECTORY
-
-echo "{ \"agentToken\":\"$agent_token\" , \"agentVersion\":\"$version\" }" > etc/config/agent-config.json
-
 
 if [ $is_root -eq 1 ] ; then
     chown -R $USERNAME:$USERNAME $INSTALLATION_DIRECTORY
 
-    echo "SeaLion-Agent: Creating /etc/init.d/sealion" >&1
+    
     cp -u /usr/local/sealion-agent/etc/sealion $INIT_FILE
     chmod +x $INIT_FILE
 
     chown $USERNAME:$USERNAME $INIT_FILE
 
-    echo "SeaLion-Agent: Creating start/stop links for /etc/init.d/sealion" >&1
-    
     for (( i = 0 ; i < 7 ; i++ )) 
     do
         ln -sf $INIT_FILE /etc/rc$i.d/${SYMLINK_PATHS[$i]}20sealion
         if [ $? -ne 0 ] ; then
-            echo "SeaLion-Agent Error: Unable to update init.d files. Quiting" >&2
+            echo "Error: Unable to update init.d files. Aborting" >&2
             clean_up $i
             exit 1
         fi
         chown -h $USERNAME:$USERNAME /etc/rc$i.d/${SYMLINK_PATHS[$i]}20sealion
     done
-
+    
+    echo "Installed SeaLion as a service" >&1
+    
 else
 
     cat etc/sealion > $INIT_FILE
 
 fi
 
-rm -rf $TMP_FILE_PATH
-if [ $? -ne 0 ] ; then
-    echo "SeaLion-Agent Error: Error in deleting temporary files" >&2
+
+if [ -z $agent_id ] ; then
+
+    if [ -z $tags ] ; then
+
+        return_code=`curl -s -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "{\"orgToken\":\"$org_token\", \"name\":\"$host\"}" https://api.sealion.com/agents -o $TMP_DATA_NAME`
+        if [ $? -ne 0 -o $return_code -ne 201 ] ; then
+            clean_up 6
+            echo "Error: Registration failed. Aborting" >&2
+            exit 123
+        fi     
+    else
+        tags=\"$tags\"
+        tags=${tags//,/\",\"}
+        return_code=`curl -s -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "{\"orgToken\":\"$org_token\", \"name\":\"$host\", \"category\":$tags}" https://api.sealion.com/agents -o $TMP_DATA_NAME`
+        if [ $? -ne 0 -o $return_code -ne 201 ] ; then
+            clean_up 6
+            echo "Error: Registration failed. Aborting" >&2
+            exit 123
+        fi
+    fi
+    
+    dataJSON=`cat $TMP_DATA_NAME`
+    
+    get_JSON_value $dataJSON
+    if [ $? -ne 0 ] ; then
+        clean_up 6
+        echo "Error: Failed to parse response. Aborting" >&2   
+        exit 121
+    fi
+    
+    if [ -z $version ] ; then
+        clean_up 6
+        echo "Error: 'agent-version' not present in response. Aborting" >&2
+        exit 119
+    fi    
+    
+    if [ -z $agent_id ] ; then
+        clean_up 6
+        echo "Error: 'agent-id' not present in response. Aborting" >&2
+        exit 120
+    fi
+    
+    if [ -z $already_registered ] ; then
+        echo "Error: 'already-registered' not present in response" >&2
+    fi
 fi
 
-echo "SeaLion-Agent: Starting Agent..." >&1
+echo "{ \"agentId\":\"$agent_id\" , \"agentVersion\":\"$version\" }" > etc/config/agent-config.json
+echo "{\"orgToken\":\"$org_token\"}" > etc/config/org-config.json
+
+rm -rf $TMP_FILE_PATH
+if [ $? -ne 0 ] ; then
+    echo "Error: Failed to delete temporary files" >&2
+fi
+
+echo "Starting agent..." >&1
 $INIT_FILE start
 if [ $? -ne 0 ] ; then
-    echo "SeaLion-Agent: Service can't be started due to errors" >&2
+    echo "Error: Service can not be started" >&2
     exit 1
 else
-    echo "SeaLion-Agent: Service successfully started, exiting installer" >&1
+    echo "Installation successfull. Please continue on https://sealion.com" >&1
     exit 0
 fi
 exit 0
